spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${BLOG_DB_NAME:root}
    password: ${BLOG_DB_PASSWORD:peb20030308#@}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      timeout: 5000


server:
  port: 8070

mybatis-plus:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.project.myblog.entity

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
