spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 10.13.7.115
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      timeout: 5000
      password: wozhidaonihenjidannixianbieji


server:
  port: 8070

mybatis-plus:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.project.myblog.entity
